# Copyright 2025 VDURA Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Functional Tests and Vulnerability Scan

on:
  pull_request:
    branches:
      - main
    paths:
      # CSI Driver source code changes
      - 'cmd/**'
      - 'pkg/**'
      - 'internal/**'
      - 'go.mod'
      - 'go.sum'

      # Deployment files changes
      - 'charts/**'
      - 'deploy/**'

      # Build files changes
      - 'Dockerfile'
      - 'Makefile'

      # Sanity tests changes
      - 'tests/**'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  csi-driver-image:
    name: CSI Driver
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-reusable.yaml
    with:
      runner-label: "ubuntu-latest"
      app-version: "${{ github.ref_name }}"
      image-name: "panfs-csi-driver"
      image-tags: "pr${{ github.event.pull_request.number }}"
      repo-url: "ghcr.io/${{ github.repository }}"
      ref: "${{ github.ref }}"
      trivy-scan: true
      sanity-tests: true
      push: true
    secrets: inherit

  deploy:
    permissions:
      id-token: write
      packages: read
      contents: read
    needs: csi-driver-image
    uses: ./.github/workflows/deploy-reusable.yaml
    with:
      driver-installation-type: "helm"
      driver-image-url: "${{ needs.csi-driver-image.outputs.image-url }}:pr${{ github.event.pull_request.number }}"
      runner-label: "ubuntu-latest"
      ref: ${{ github.ref }}
    secrets: inherit

  trivy-repo-scan:
    name: Trivy Repo Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          exit-code: '1'
          format: 'table'
          ignore-unfixed: true
          scan-type: 'fs'
          severity: 'HIGH,CRITICAL'